//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameDataDbEntities : DbContext
    {
        public GameDataDbEntities()
            : base("name=GameDataDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrencyBuy> CurrencyBuys { get; set; }
        public virtual DbSet<GameStart> GameStarts { get; set; }
        public virtual DbSet<ItemBuy> ItemBuys { get; set; }
        public virtual DbSet<StageEnd> StageEnds { get; set; }
        public virtual DbSet<StageStart> StageStarts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
